const $=s=>document.querySelector(s);
const sky=$("#sky"),ctx=sky.getContext("2d"),world=$("#world"),dialog=$("#creator"),av=$("#avatar"),ac=av.getContext("2d");
let face=0,uploaded=null,me=null,guests=[],socket=null,myId=null,lastSync=0;
const remote=new Map(), palette=()=>[$("#bodyColor").value,$("#accentColor").value];

function resize(){sky.width=innerWidth*devicePixelRatio;sky.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener("resize",resize);resize();
const stars=Array.from({length:70},()=>({x:Math.random(),y:Math.random()*.68,r:Math.random()*1.7+.3,p:Math.random()*6.28}));
function ambience(t){ctx.clearRect(0,0,innerWidth,innerHeight);stars.forEach(s=>{ctx.globalAlpha=.25+.5*(.5+.5*Math.sin(t/900+s.p));ctx.fillStyle="#f4efd9";ctx.beginPath();ctx.arc(s.x*innerWidth,s.y*innerHeight,s.r,0,7);ctx.fill()});ctx.globalAlpha=1;requestAnimationFrame(ambience)}requestAnimationFrame(ambience);

function pixel(){ac.save();ac.clearRect(0,0,512,512);ac.scale(32,32);let [b,a]=palette();ac.fillStyle=b;ac.fillRect(4,4,8,9);ac.fillRect(3,6,10,5);ac.fillStyle=a;ac.fillRect(5,2,6,3);ac.fillRect(4,3,8,1);ac.fillRect(3,12,4,3);ac.fillRect(9,12,4,3);ac.fillStyle="#f3d9bd";ac.fillRect(5,5,6,5);ac.fillStyle="#14221f";let eyes=face===1?[[6,6],[10,6]]:[[6,7],[10,7]];eyes.forEach(([x,y])=>ac.fillRect(x,y,1,1));if(face===0)ac.fillRect(7,9,3,1);if(face===1){ac.fillRect(7,8,1,1);ac.fillRect(8,9,2,1);ac.fillRect(10,8,1,1)}if(face===2){ac.fillRect(7,9,1,1);ac.fillRect(9,9,1,1)}if(face===3)ac.fillRect(7,8,3,1);ac.restore()}
pixel();["bodyColor","accentColor"].forEach(id=>$("#"+id).addEventListener("input",()=>{uploaded=null;pixel()}));
document.querySelectorAll("[data-face]").forEach(b=>b.onclick=()=>{face=+b.dataset.face;uploaded=null;document.querySelectorAll("[data-face]").forEach(x=>x.classList.remove("active"));b.classList.add("active");pixel()});document.querySelector("[data-face='0']").classList.add("active");
$("#upload").onchange=e=>{let f=e.target.files[0];if(!f)return;if(f.size>3*1024*1024){alert("Please choose an image under 3 MB.");e.target.value="";return}let im=new Image();im.onload=()=>{ac.clearRect(0,0,16,16);ac.imageSmoothingEnabled=false;let side=Math.min(im.width,im.height),sx=(im.width-side)/2,sy=(im.height-side)/2;ac.imageSmoothingEnabled=true;ac.imageSmoothingQuality="high";ac.drawImage(im,sx,sy,side,side,0,0,512,512);uploaded=av.toDataURL("image/webp",.9);URL.revokeObjectURL(im.src)};im.src=URL.createObjectURL(f)};

function updateCount(){let n=guests.length;$("#guestCount").textContent=n+" "+(n===1?"guest is":"guests are")+" wandering around"}
function addGuest(data,isMe=false,id=null){let g=document.createElement("div");g.className="guest"+(isMe?" me":"");g.innerHTML='<span class="bubble"></span><img class="sprite" alt=""><span class="shadow"></span>';g.querySelector(".bubble").textContent=data.name||"guest";g.querySelector("img").src=data.image;world.appendChild(g);let obj={id,el:g,x:Number.isFinite(data.x)?data.x*innerWidth:(isMe?innerWidth*.48:Math.random()*innerWidth),v:Number.isFinite(data.v)?data.v:(Math.random()>.5?1:-1)*(.18+Math.random()*.18),phase:Math.random()*8,isMe};guests.push(obj);if(id&&!isMe)remote.set(id,obj);updateCount();return obj}
function removeGuest(id){let g=remote.get(id);if(!g)return;g.el.classList.add("leaving");setTimeout(()=>g.el.remove(),250);guests=guests.filter(x=>x!==g);remote.delete(id);updateCount()}
function upsertRemote(p){if(!p||p.id===myId||!p.avatar)return;let g=remote.get(p.id);if(!g){addGuest({name:p.avatar.name,image:p.avatar.image,x:p.x,v:p.v},false,p.id);return}g.el.querySelector(".bubble").textContent=p.avatar.name||"guest";if(g.el.querySelector("img").src!==p.avatar.image)g.el.querySelector("img").src=p.avatar.image;if(Number.isFinite(p.x))g.x=p.x*innerWidth;if(Number.isFinite(p.v))g.v=p.v}
function send(type,payload={}){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify({type,...payload}))}
function connect(){if(location.protocol==="file:")return;let proto=location.protocol==="https:"?"wss":"ws";socket=new WebSocket(proto+"://"+location.host+"/ws");socket.onopen=()=>{$("#connection").className="connection online";$("#connection").textContent="LIVE";let saved=getSaved();if(saved)send("join",{avatar:saved,x:me?me.x/innerWidth:.5,v:me?.v||.22})};socket.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==="welcome"){myId=m.id;(m.guests||[]).forEach(upsertRemote)}if(m.type==="guest")upsertRemote(m.guest);if(m.type==="leave")removeGuest(m.id)};socket.onclose=()=>{$("#connection").className="connection";$("#connection").textContent="RECONNECTING";setTimeout(connect,1500)};socket.onerror=()=>socket.close()}
function getSaved(){try{return JSON.parse(localStorage.getItem("waiting-avatar"))}catch{return null}}

function animateGuests(t){let w=innerWidth;guests.forEach(g=>{if(g.isMe){g.x+=g.v;if(g.x>w-70){g.x=w-70;g.v*=-1}if(g.x<0){g.x=0;g.v*=-1}}else{g.x+=g.v*.35;if(g.x>w-70||g.x<0)g.v*=-1}let sway=Math.sin(t/1200+g.phase)*5;g.el.style.transform='translate3d('+g.x+'px,'+sway+'px,0) scaleX('+(g.v<0?-1:1)+')';g.el.querySelector(".bubble").style.transform='scaleX('+(g.v<0?-1:1)+')'});if(me&&t-lastSync>900){lastSync=t;send("move",{x:Math.max(0,Math.min(1,me.x/w)),v:me.v})}requestAnimationFrame(animateGuests)}requestAnimationFrame(animateGuests);

function saveAndJoin(e){e?.preventDefault();let data={name:$("#name").value.trim().slice(0,18)||"guest",image:uploaded||av.toDataURL("image/webp",.9)};localStorage.setItem("waiting-avatar",JSON.stringify(data));if(me){me.el.querySelector("img").src=data.image;me.el.querySelector(".bubble").textContent=data.name}else me=addGuest(data,true);send("join",{avatar:data,x:me.x/innerWidth,v:me.v});dialog.close()}
$("#joinBtn").onclick=saveAndJoin;$("#editBtn").onclick=()=>dialog.showModal();
let saved=getSaved();if(saved){me=addGuest(saved,true);$("#name").value=saved.name||""}else setTimeout(()=>dialog.showModal(),500);
connect();
